# Generated by Django 5.0.6 on 2024-06-13 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('city_name', models.CharField(max_length=30)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.state')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.IntegerField()),
                ('dt_iso', models.CharField(max_length=255)),
                ('timezone', models.IntegerField()),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.state')),
            ],
        ),
        migrations.CreateModel(
            name='Snow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_hour', models.FloatField(null=True)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.state')),
                ('dt_iso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.time')),
            ],
        ),
        migrations.CreateModel(
            name='Rain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_hour', models.FloatField(null=True)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.state')),
                ('dt_iso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.time')),
            ],
        ),
        migrations.CreateModel(
            name='Clouds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all', models.IntegerField()),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.state')),
                ('dt_iso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.time')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('dew_point', models.FloatField()),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.city')),
                ('dt_iso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.time')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.state')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_id', models.IntegerField(null=True)),
                ('main', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.city')),
                ('dt_iso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.time')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.state')),
            ],
        ),
        migrations.CreateModel(
            name='Wind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField()),
                ('deg', models.IntegerField()),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.city')),
                ('dt_iso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.time')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.state')),
            ],
        ),
    ]
